# Generated by Django 5.1.1 on 2024-10-30 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabarticle', '0002_rename_category_category_topic_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(choices=[('Sports', 'Sports'), ('Business', 'Business'), ('Politics', 'Politics')], null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blabarticle.category'),
        ),
    ]
