# Generated by Django 5.1.1 on 2024-10-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabarticle', '0005_article_published_category_alter_category_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
