# Generated by Django 5.1.1 on 2024-10-31 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabarticle', '0006_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published_category',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blabarticle.category'),
        ),
    ]
