# Generated by Django 5.1.1 on 2024-10-31 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabarticle', '0008_auto_20241031_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='topic',
            new_name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='published_category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Business', 'Business'), ('Politics', 'Politics')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blabarticle.category'),
        ),
    ]
